//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleHmi.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Mainpage : global::System.Configuration.ApplicationSettingsBase {
        
        private static Mainpage defaultInstance = ((Mainpage)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Mainpage())));
        
        public static Mainpage Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int RoterJogSpeed {
            get {
                return ((int)(this["RoterJogSpeed"]));
            }
            set {
                this["RoterJogSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int RoterPositioningSpeed {
            get {
                return ((int)(this["RoterPositioningSpeed"]));
            }
            set {
                this["RoterPositioningSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RoterCommendposition {
            get {
                return ((int)(this["RoterCommendposition"]));
            }
            set {
                this["RoterCommendposition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int RoteryPosJogSpeed {
            get {
                return ((int)(this["RoteryPosJogSpeed"]));
            }
            set {
                this["RoteryPosJogSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int RoteryPosPositioningSpeed {
            get {
                return ((int)(this["RoteryPosPositioningSpeed"]));
            }
            set {
                this["RoteryPosPositioningSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RoteryPosCommendposition {
            get {
                return ((int)(this["RoteryPosCommendposition"]));
            }
            set {
                this["RoteryPosCommendposition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ShorterJogSpeed {
            get {
                return ((int)(this["ShorterJogSpeed"]));
            }
            set {
                this["ShorterJogSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int ShorterPositioningSpeed {
            get {
                return ((int)(this["ShorterPositioningSpeed"]));
            }
            set {
                this["ShorterPositioningSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ShorterCommendposition {
            get {
                return ((int)(this["ShorterCommendposition"]));
            }
            set {
                this["ShorterCommendposition"] = value;
            }
        }
    }
}
